function createPanelSingleRun(obj,hPanel,~)

% set panel position
tmp = obj.h.protocol.panel.main;
pos = [sum(tmp.Position([1 3]))+6 tmp.Position(2) obj.h.fig.Position(3)-sum(tmp.Position([1 3]))-14 60];
set(hPanel, ...
    'Units',    'Pixels', ...
    'Position', pos, ...
    'Title',  	'Single Stimulation')

szCtrl  = [45 21];
pad     = 3;
obj.h.singleRun.push.start = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[5 5 szCtrl],...
    'String',  	'Start', ...
    'Callback', @obj.callbackSingleRunStart);
tmp = obj.h.singleRun.push.start.Position;
obj.h.singleRun.push.stop = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[sum(tmp([1 3]))+pad 5 szCtrl],...
    'String',  	'Stop', ...
    'Callback', @obj.callbackProtocolStop,...
    'Enable',   'off');