function createPanelProtocol(obj,hPanel,~)

% set panel position
tmp = obj.h.animal.panel.main;
pos = [sum(tmp.Position([1 3]))+6 tmp.Position(2) 50 60];
set(hPanel, ...
    'Units',    'Pixels', ...
    'Position', pos, ...
    'Title',  	'Protocol')

szCtrl1 = [45 21];
szCtrl2 = [20 21];
pad     = 3;
obj.h.protocol.push.prev = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[5 5 szCtrl2],...
    'String',  	'<', ...
    'Callback', @obj.callbackProtocolNstim);
obj.h.protocol.edit.nStim = ...
    uicontrol(hPanel,...
    'Style',  	'edit', ...
    'Position',	[sum(obj.h.protocol.push.prev.Position([1 3]))+pad 6 szCtrl1-[0 2]],...
    'String',  	'', ...
    'Callback', @obj.callbackProtocolNstim);
obj.h.protocol.push.next = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[sum(obj.h.protocol.edit.nStim.Position([1 3]))+pad 5 szCtrl2],...
    'String',  	'>', ...
    'Callback', @obj.callbackProtocolNstim);
obj.h.protocol.text.nStim = ...
    uicontrol(hPanel,...
    'Style',                'Text',...
    'Position',             [5 5+szCtrl1(2) szCtrl1(1)+szCtrl2(1)*2+pad*2 14],...
    'String',               'Stimulus Number', ...
    'HorizontalAlignment',  'left');

obj.h.protocol.edit.Comment = ...
    uicontrol(hPanel,...
    'Style',                'Edit',...
    'Position',             [sum(obj.h.protocol.push.next.Position([1 3]))+3*pad 6 350 szCtrl1(2)-2],...
    'String',               '', ...
    'Enable',               'off', ...
    'HorizontalAlignment',  'left');
tmp = obj.h.protocol.edit.Comment.Position;
obj.h.protocol.text.nStim = ...
    uicontrol(hPanel,...
    'Style',                'Text',...
    'Position',             [tmp(1) 5+szCtrl1(2) tmp(3) 14],...
    'String',               'Comment', ...
    'HorizontalAlignment',  'left');

obj.h.protocol.push.start = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[sum(tmp([1 3]))+3*pad obj.h.protocol.push.prev.Position(2) 40 szCtrl2(2)],...
    'String',  	'Start', ...
    'Callback', @obj.callbackProtocolStart);
tmp = obj.h.protocol.push.start.Position;
obj.h.protocol.push.stop = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[sum(tmp([1 3]))+pad tmp(2) 40 szCtrl2(2)],...
    'String',  	'Stop', ...
    'Callback', @obj.callbackProtocolStop);

hPanel.Position(3) = sum(obj.h.protocol.push.stop.Position([1 3])) + 6;
set(hPanel.Children,'Enable','off')