function createPanelAnimal(obj,hPanel,~)


% set panel position
pos = [10 sum(obj.h.ThermodeA.panel.params.Position([2 4]))+6 248 60];
set(hPanel, ...
    'Units',    'Pixels', ...
    'Position', pos, ...
    'Title',  	'Animal')

% create dropdown menu
obj.h.animal.listbox.id = uicontrol(hPanel,...
    'Style',    'popupmenu',...
    'String',   '',...
    'Position', [5 4 179 21]);
obj.updateAnimals()
obj.h.animal.text.id = ...
    uicontrol(hPanel,...
    'Style',                'Text',...
    'Position',             [5 26 obj.h.animal.listbox.id.Position(3) 14],...
    'String',               'ID / subfolder', ...
    'HorizontalAlignment',  'left');

obj.h.animal.push.add = ...
    uicontrol(hPanel,...
    'Style',  	'PushButton',...
    'Position',	[sum(obj.h.animal.listbox.id.Position([1 3]))+3 5 20 21],...
    'String',  	'+', ...
    'Callback', @obj.callbackAnimalAdd);

hPanel.Position(3) = sum(obj.h.animal.push.add.Position([1 3])) + 6;