classdef CameraComponentProperties < ComponentProperties
properties (Constant)
    ID = ComponentProperty( ...
        'default'     , '', ...
        'note'        , 'used to distinguist between multiple devices')
    ProtocolID = ComponentProperty( ...
        'default'     , 'Widefield', ...
        'ValidateFcn' , @(x) isstring(x) || ischar(x), ...
        'dynamic'     , true, ...
        'note'        , 'Used with ProtocolType to connect hardware to experiment protocol files')
    Adaptor = ComponentProperty( ...
        'default'     , 'gentl', ... 
        'editable'    , false, ...
        'allowable'   , imaqhwinfo().InstalledAdaptors, ...
        'validatefcn' , @(x) isstring(x) || ischar(x), ...
        'dependents'  , {'Binning', 'BinningType'}, ...
        'note'        , 'Any MATLAB-supported camera adaptor.')
    Binning = ComponentProperty( ...
        'default'     , 1, ...
        'allowable'   , [1, 2, 4], ...
        'dynamic'     , false, ...
        'dependencies', @(propStruct) strcmpi(propStruct.Adaptor, 'gentl') || ...
                        strcmpi(propStruct.Adaptor, 'pcocameraadaptor'))
    BinningType = ComponentProperty( ...
        'default'     , 'Sum', ...
        'allowable'   , {'Sum', 'Other'}, ...
        'dynamic'     , false, ...
        'dependencies', @(propStruct) strcmpi(propStruct.Adaptor, 'gentl') || ...
                        strcmpi(propStruct.Adaptor, 'pcocameraadaptor') ... %copied and pasted from binning
        )
    ExposureTime = ComponentProperty( ...
        'default'     , '10000', ...
        'validatefcn' , @(x) (~isnan(str2double(x)) && str2double(x)>=21) || ...
                            (isnumeric(x) && length(x)==1 && x>=21 && ~isnan(x)), ...
        'dynamic'     , true, ...
        'note'        , '')
    FramesPerTrigger = ComponentProperty( ...
        'default'     , '1', ...
        'validatefcn' , @(x) strcmpi(x, '1') || (isnumeric(x) && length(x)==1 && x==1), ...
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware') || ...
                        strcmpi(propStruct.TriggerMode, 'manual'), ...
        'dynamic'     , true, ...
        'note'        , 'Ideally any number will be permitted but not yet')
    Gain = ComponentProperty( ...
        'default'     , '20', ...
        'validatefcn' , @(x) (~isnan(str2double(x)) && str2double(x)>=0 && str2double(x)<=36) ...
                            || (isnumeric(x) && length(x)==1 && 0<=x && x<=36), ...
        'dynamic'     , true, ...
        'note'        , 'dB. Max of 36.')
    OutputLine = ComponentProperty( ...
        'default'     , 'Line3', ...
        'allowable'   , {'Line3', 'Line4'}, ...
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'immediate'), ...
        'dynamic'     , true, ...
        'note'        , 'Depends on specific camera hardware.')
    TriggerActivation = ComponentProperty( ...
        'default'     , 'RisingEdge', ...
        'allowable'   , {'RisingEdge', 'FallingEdge', 'none'}, ... 
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware'), ...
        'dynamic'     , false, ...
        'note'        , 'Depends on specific camera hardware.')
    TriggerMode = ComponentProperty( ...
        'default'     , 'hardware', ...
        'allowable'   , {'hardware', 'manual', 'immediate'}, ...
        'dynamic'     , false, ...
        'dependents'  , {'TriggerActivation', 'TriggerSelector', 'FramesPerTrigger', 'OutputLine'}, ...
        'note'        , ['hardware: GPIO-triggered, manual: software-triggered, ', ...
                        'immediate: camera-driven acquisition.'])
    TriggerLine = ComponentProperty( ...
        'default'     , 'Line4', ...
        'allowable'   , {'Line3', 'Line4'}, ... 
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware'), ...
        'dynamic'     , true, ...
        'note'        , 'Depends on specific camera hardware.')
    TriggerFrameDelay = ComponentProperty( ...
        'default'     , 0, ...
        'validatefcn' , @(x) isnumeric(x), ...
        'dynamic'     , true)
    FrameGrabInterval = ComponentProperty( ...
        'default'     , 1, ...
        'allowable'   , [], ...
        'validatefcn' , @(x) isnumeric(x) && x > 0, ...
        'dynamic'     , true, ...
        'note'        , ['Number of frames to have captured before ', ...
                        'activating framesavailable'])
    TriggerRepeat = ComponentProperty( ...
        'default'     , Inf, ...
        'validatefcn' , @(x) length(x)==1 && isnumeric(x) && x > 0, ...
        'dynamic'     , false, ...
        'note'        , ['Number of frames to capture before the camera closes itself. ', ...
                        'Ideally indefinite but unclear if that is supported'])
    ROIPosition = ComponentProperty( ...
        'default'     , '', ...
        'validatefcn' , @(x) ((ischar(x) || isstring(x)) && (isempty(x) || any(regexpi(x, "^(\d+( )+){3}\d+$")))) ...
                            || (isnumeric(x) && length(x) == 4 && all(x>=0)), ...
        'dynamic'     , false, ...
        'note'        , 'ROI, set programmatically. If empty, defaults to full camera FOV')
    TriggerSelector = ComponentProperty( ...
        'default'     , 'FrameStart', ...
        'allowable'   , [], ... 
        'dynamic'     , false, ...
        'dependencies', @(propStruct) strcmpi(propStruct.TriggerMode, 'hardware') || ...
                        strcmpi(propStruct.TriggerMode, 'manual'))
    TrialTimeout = ComponentProperty( ...
        'default'     , 3, ...
        'validatefcn' , @(x) isnumeric(x), ...
        'note'        , 'how long to wait without acquiring new data before the camera no longer registers as acquiring')
end

methods (Static, Access=private)
    function out = GetDefaultAdaptor()
        if isempty(imaqhwinfo().InstalledAdaptors)
            out = '';
        else
            out = imaqhwinfo().InstalledAdaptors{1};
        end
    end
end

methods (Access=public)
    function componentID = GetComponentID(obj)
        componentID = convertStringsToChars([obj.Adaptor '-' obj.ProtocolID]);
        if iscell(componentID)
            componentID = [componentID{:}];
        end
    end
end
end