classdef SerialComponentProperties < ComponentProperties
properties (Constant)
ID = ComponentProperty( ...
    'default', "COM5", ...
    'validatefcn', @(x) isstring(x) || ischar(x))
ProtocolID = ComponentProperty( ...
    'default', 'QST', ...
    'dynamic', true, ...
    'validatefcn', @(x) isstring(x) || ischar(x))
Port = ComponentProperty( ...
    'default', SerialComponentProperties.GetLastAvailablePort, ...
    'allowable', SerialComponentProperties.GetAvailablePorts, ...
    'note', 'The physical serial port to which the component is connected.')
BaudRate = ComponentProperty( ...
    'default', 115200, ...
    'validatefcn', @(x) (isnumeric(x) && x > 0) || ~isnan(str2double(x)) && str2double(x)>=0, ...
    'note', 'Baud rate, symbols/sec')
InputBufferSize = ComponentProperty( ...
    'default', 4096, ...
    'validatefcn', @(x) (isnumeric(x) && x > 0) || ~isnan(str2double(x)) && str2double(x)>=0, ...
    'note', 'Input buffer size, bits')
Terminator = ComponentProperty( ...
    'default', 'CR', ...
    'validatefcn', @(x) isstring(x) || ischar(x), ... %TODO more involved than this.
    'note', 'Used to initialise')
Tag = ComponentProperty( ...
    'default', 'QST', ...
    'validatefcn', @(x) isstring(x) || ischar(x), ...
    'note', 'Distinguishes between multiple serial sessions.')
PingValue = ComponentProperty( ...
    'default', 'H', ...
    'validatefcn', @(x) isstring(x) || ischar(x), ...
    'note', 'Used to check connectivity')
SoftwareTriggerCommand = ComponentProperty( ...
    'default', 'L', ...
    'validatefcn', @(x) isstring(x) || ischar(x), ...
    'note', 'Used to trigger the serial device')
    % Protocol = ComponentProperty( ...
    %     'validatefcn', @(x) isstring(x) || ischar(x), ...
    %     'default', DAQComponentProperties.GetDefaultChannelConfig))
end
methods (Static, Access=private)
function out = GetAvailablePorts()
    if isMATLABReleaseOlderThan('R2024b')
         warning('off', 'instrument:seriallist:FunctionToBeRemoved');
            out = seriallist; %#ok<*SERLL>
        warning('on', 'instrument:seriallist:FunctionToBeRemoved');
    else
        out = cellstr(serialportlist);
    end
end

function out = GetLastAvailablePort()
    ports = SerialComponentProperties.GetAvailablePorts();
    out = ports{end};
end
end
end