function createPanelLED(obj,hPanel,~)

% set panel position
pos = [10 10 obj.h.fig.Position(3)-18 122];
set(hPanel, ...
    'Units',    'Pixels', ...
    'Position', pos, ...
    'Title',  	'LED')

szCtrl = [34 21];
wdText = 130;
pad    = 3;

% define control labels and tags
labels = {'Duration (ms)', 'Frequency (Hz)', 'Duty Cycle (%)', 'Delay (ms)'};
tags   = {'ledDur', 'ledFreq', 'ledDC', 'ledDelay'};
def    = {'0' '25.0' '50' '0'};

x      = hPanel.Position(3)-370+wdText+pad;
for idxParam = 1:length(tags)
    y  = pos(4)-12-idxParam*(szCtrl(2)+pad)-pad;
    
    % create control
    obj.h.LED.edit.(tags{idxParam}) = ...
        uicomponent(hPanel,...
        'Style',  	'Edit',...
        'Position',	[x y szCtrl],...
        'Tag',    	tags{idxParam},...
        'String',   def{idxParam},...
        'Value',    str2double(def{idxParam}),...
        'Callback', @obj.callbackLEDEdit);
        
    % create control labels
    obj.h.LED.label.tags{idxParam} = ...
        uicontrol(hPanel,...
        'Style',                'Text',...
        'Position',             [hPanel.Position(3)-370 y-4 wdText szCtrl(2)],...
        'String',               labels{idxParam},...
        'HorizontalAlignment', 'right',...
        'Tag',                  tags{idxParam});
end

% create axes
obj.h.LED.panel.axes = uipanel(hPanel, ...
    'Units',           'Pixels',...
    'BorderType',      'beveledin',...
    'backgroundcolor', 'w',...
    'Position',        [6 6 hPanel.Position(3:4)-[380 25]]);
obj.h.LED.axes = axes(obj.h.LED.panel.axes, ...
    'FontName',             'Segoe UI', ...
    'Fontsize',             7, ...
    'FontSmoothing',        'on', ...
    'TickDir',              'out', ...
    'Color',                'none', ...
    'Units',                'pixels', ...
    'Nextplot',             'add', ...
    'XLim',                 [-5 10], ...
    'YLim',                 [0 1], ...
    'XMinorGrid',           'on', ...
    'YGrid',                'on', ...
    'MinorGridLineStyle',   '-', ...
    'MinorGridColor',       [1 1 1].*.7, ...
	'GridLineStyle',        '-', ...
    'GridColor',            [1 1 1].*.7, ...
    'Tag',                  'LED', ...
    'Layer',                'top', ...
    'YTick',                [0 1], ...
    'YTickLabel',           {'off','on'});
xlabel('Time (s)')
ylabel('State')
fill([0 1],[0 0],'r','edgecolor','none')
obj.setAxesPadding(obj.h.LED.axes,4)

% we obviously need a chicken
[img,~,alpha] = imread('chicken.png');
obj.h.LED.chicken = axes(hPanel, ...
    'Units',        'pixels', ...
    'Position',     [hPanel.Position(3)-size(img,2)-10 7 size(img,2) size(img,1)], ...
    'Color',        'none');
axis equal
f = imshow(img);
set(f,'AlphaData', alpha);

obj.createPlotLED(obj.h.LED.axes)