function createPanelThermode(obj,hPanel,~,idxThermode,nThermodes)

% set panel position
IDthermode = ['Thermode' char(64+idxThermode)];
pos = [10 obj.h.LED.panel.params.Position(4)+ ...
    (nThermodes-idxThermode)*(245+6)+16 obj.h.fig.Position(3)-18 245];
set(hPanel, ...
    'Units',    'Pixels', ...
    'Position', pos, ...
    'Title',  	['Thermode ' IDthermode(end)])

szCtrl = [34 21];
wdText = 130;
pad    = 3;

% define control labels and tags
labels = {'Toggle Surface','Setpoint Temperature (°C)',...
    'Pacing Rate (°C/s)', 'Return Speed (°C/s)', ...
    'Stimulus Duration (ms)','Neutral Temperature (°C)','Battery', ...
    'Vibration Duration (ms)','LED Duration (ms)','LED Frequency (Hz)',...
    'LED Duty Cycle (%)'};
tags   = {'S','C','V','R','D','N','B','X'};

for idxParam = 1:length(tags)
    tag1 = tags{idxParam};
    tag2 = sprintf('%s%s',IDthermode(end),tag1);
    y    = pos(4)-15-idxParam*(szCtrl(2)+pad)-5-pad;
    if idxParam>5 && idxParam<=7
        y = y-10;
    elseif idxParam>7
        y = y-20;
    end
    
    % create control labels
    obj.h.(IDthermode).label.(tag1) = ...
        uicontrol(hPanel,...
        'Style',                'Text',...
        'Position',             [hPanel.Position(3)-370 y-4 wdText szCtrl(2)],...
        'String',               labels{idxParam},...
        'HorizontalAlignment', 'right',...
        'Tag',                  tag2);
    
    % get color order
    tmp = axes;
    colorOrder = get(tmp,'colororder');
    delete(tmp)
    
    for idxSurf = 1:5
        x    = hPanel.Position(3)-370+wdText+pad+(idxSurf-1)*(szCtrl(1)+pad);
        tag3 = sprintf('%s%d',tag2,idxSurf);
        
        % create legend for color code and toggle buttons
        if idxParam == 1
            uipanel(hPanel,...
                'Units',            'pixels',...
                'Position',         [x y+szCtrl(2)+pad szCtrl(1) 10], ...
                'BorderType',       'beveledin', ...
                'BackgroundColor',  colorOrder(idxSurf,:));
            obj.h.(IDthermode).toggle.(tag1)(idxSurf) = ...
                uicontrol(hPanel,...
                'Style',    'ToggleButton',...
                'Position', [x y szCtrl],...
                'String',   idxSurf,...
                'Tag',      tag3,...
                'Callback', @obj.callbackThermodeToggle);
            
            % create edit fields (per-surface)
        elseif ismember(idxParam,2:5)
            obj.h.(IDthermode).edit.(tag1)(idxSurf) = ...
                uicontrol(hPanel,...
                'Style',    'Edit',...
                'Position', [x y szCtrl],...
                'Tag',      tag3,...
                'Callback', @obj.callbackThermodeEdit);
            
            % create fields for stimulus number (including binary)
        elseif idxParam==6 && idxSurf == 1
            obj.h.(IDthermode).edit.(tag1) = ...
                uicontrol(hPanel,...
                'Style',    'Edit',...
                'Position', [x y szCtrl],...
                'Tag',      tag2,...
                'Callback', @obj.callbackThermodeEdit);

            % battery indicator
        elseif idxParam == 7 && idxSurf == 1
            obj.h.(IDthermode).battery = ...
                uicomponent(hPanel,...
                'Style',        'JProgressbar',...
                'Position',     [x y szCtrl],...
                'Value',        0,...
                'StringPainted',1);
            
        elseif idxParam == 8 && idxSurf == 1
            obj.h.(IDthermode).edit.vibDur = ...
                uicomponent(hPanel,...
                'Style',  	'Edit',...
                'Position',	[x y szCtrl],...
                'Tag',    	tag2,...
                'String',   0,...
                'Callback', @obj.callbackThermodeEdit);
        end
    end
    
    if ismember(idxParam,2:5)
        % create synchronization checkboxes
        obj.h.(IDthermode).check.(tag1) = ...
            uicontrol(hPanel,...
            'Style',    'checkbox', ...
            'Position', [x+szCtrl(1)+pad y 50 szCtrl(2)], ...
            'String',  	'sync',...
            'Tag',    	tag2,...
            'Value',    true,...
            'Callback', @obj.callbackThermodeSync);
    end
end
obj.h.(IDthermode) = orderfields(obj.h.(IDthermode));


% create axes
obj.h.(IDthermode).panel.axes = uipanel(hPanel, ...
    'Units',           'Pixels',...
    'BorderType',      'beveledin',...
    'backgroundcolor', 'w',...
    'Position',        [6 6 hPanel.Position(3:4)-[380 25]]);
obj.h.(IDthermode).axes = axes(obj.h.(IDthermode).panel.axes, ...
    'FontName',             'Segoe UI', ...
    'Fontsize',             7, ...
    'FontSmoothing',        'on', ...
    'TickDir',              'out', ...
    'Color',                'none', ...
    'Units',                'pixels', ...
    'Nextplot',             'add', ...
    'XLim',                 [-5 10], ...
    'YLim',                 [20 40], ...
    'XMinorGrid',           'on', ...
    'YMinorGrid',           'on', ...
    'MinorGridLineStyle',   '-', ...
    'MinorGridColor',       [1 1 1].*.7, ...
    'Tag',                  IDthermode(end));
xlabel('Time (s)')
ylabel('Temperature (°C)')
plot(obj.h.(IDthermode).axes,1:10,1:10)
obj.setAxesPadding(obj.h.(IDthermode).axes,4)