function createFigure(obj)
% https://au.mathworks.com/help/matlab/creating_guis/choose-components-for-your-app-designer-app.html
% https://au.mathworks.com/help/matlab/creating_guis/create-and-run-a-simple-programmatic-app.html
% https://au.mathworks.com/help/matlab/develop-apps-programmatically.html?s_tid=CRUX_lftnav
obj.h.fig = uifigure(...
    'Position',         [100,0,1092,657], ...
    'Units',            'Pixels', ...
    'Name',             obj.name, ...
    'CloseRequestFcn',  @obj.callbackFileExit, ...
    'GraphicsSmoothing','on');

%% Make base tabs and grids
obj.h.baseGrid = uigridlayout(obj.h.fig, ...
    'RowHeight', {'1x'}, ...
    'ColumnWidth', {'1x'});
obj.h.tabs = uitabgroup(obj.h.baseGrid, ...
    'SelectionChangedFcn', @obj.callbackChangeTab);

%% create menu
obj.h.menuTools      = uimenu(obj.h.fig, ...
    'Label',        'Tools');
obj.h.menuFixes = uimenu(obj.h.fig, ...
    "Text", "Fix");
obj.h.menuDebug = uimenu(obj.h.menuFixes, ...
    'Label',        'Debug', ...
    'Callback',     @(src, event)obj.callbackDebug(src, event));
obj.h.menuClearMsg = uimenu(obj.h.menuFixes, ...
    'Text', 'Clear Error Message', ...
    'Callback', @(src, event)obj.clearMsg(src, event));
obj.h.menuRestartTimer = uimenu(obj.h.menuFixes, ...
    'Text', 'Restart Timer', ...
    'Callback', @(src, event)RestartTimer(obj, src, event));
obj.h.menuCheckStimulus = uimenu(obj.h.menuTools, ...
    'Label', 'Check Stimulus', ...
    'Callback', @(src, event)obj.callbackLoadProtocol(src, event));

%% Setup Tab
obj.h.Setup.Tab = uitab(obj.h.tabs, 'Title', 'Setup');
obj.h.Setup.Grid = uigridlayout(obj.h.Setup.Tab, ...
    'RowHeight', {'1x', 180, 70}, ...
    'ColumnWidth', {'1x', 70, 180});

obj.h.Preview.panel.params = uipanel(obj.h.Setup.Grid, ...
    'CreateFcn', @obj.createPanelPreview, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column',1));

obj.h.Setup.Control.panel.params = uipanel(obj.h.Setup.Grid, ...
    'CreateFcn', @obj.createPanelSetupControl, ...
    'Title', 'Setup', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [2 3], ...
        'Column',1));
obj.h.Setup.ComponentConfig.panel.params = uipanel(obj.h.Setup.Grid, ...
    'CreateFcn', @obj.createPanelComponentConfig, ...
    'Title', 'Component Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [1, 2], ...
        'Column', [2 3]));
obj.h.Setup.Logo = uiimage(obj.h.Setup.Grid, ...
    "ImageSource", [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'WhitmireLogo.png'], ...
    "ScaleMethod", "fit", ...
    "ImageClickedFcn", @(src, event)obj.clearMsg(src, event), ...
    "Layout", matlab.ui.layout.GridLayoutOptions( ...
        'Row',3, ...
        'Column',2));
obj.h.Setup.Message = uilabel(obj.h.Setup.Grid, ...
    "Text", "Welcome to StimControl!", ...
    "Layout", matlab.ui.layout.GridLayoutOptions( ...
        'Row',3, ...
        'Column',3), ...
    "WordWrap", "on");

%% Session Tab
obj.h.Session.Tab = uitab(obj.h.tabs, 'Title', 'Experiment');
obj.h.Session.Grid = uigridlayout(obj.h.Session.Tab, ...
    'RowHeight', {'1x', 100}, ...
    'ColumnWidth', {'1x', 70, 180});

obj.h.Session.Control.panel.params = uipanel(obj.h.Session.Grid, ...
    'CreateFcn', @obj.createPanelSessionControl, ...
    'Title', 'Session Controls', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [2 3]));
obj.h.Session.HardwareStatus.panel.params = uipanel(obj.h.Session.Grid, ...
    'CreateFcn', @obj.createPanelSessionHardware, ...
    'Title', 'Component Status', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', 1));
obj.h.Session.Logo = uiimage(obj.h.Session.Grid, ...
    "ImageSource", [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'WhitmireLogo.png'], ...
    "ScaleMethod", "fit", ...
    "ImageClickedFcn", @(src, event)obj.clearMsg(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', 2));

obj.h.Session.Message = uilabel(obj.h.Session.Grid, ...
    "Text", "Welcome to StimControl!", ...
    "Layout", matlab.ui.layout.GridLayoutOptions( ...
        'Row',2, ...
        'Column',3), ...
    "WordWrap","on");

if isempty(obj.d.Available)
    displayText = sprintf("Welcome to StimControl! \nNo devices found. Please check you have devices connected, then restart StimControl.");
    obj.h.Setup.Message.Text = displayText;
    obj.h.Session.Message.Text = displayText;
end

%% helper functions
function varargout = RestartTimer(obj, src, event)
    stop(obj.t);
    start(obj.t);
end
end
