function createPanelSetupControl(obj, hPanel, ~)
% CREATEPANELSETUPCONTROL creates the panel for control of setup - session
% select, component edit button, etc.
grid = uigridlayout(hPanel);
grid.RowHeight = {'1x', '0.01x', 22, 22};
grid.ColumnWidth = {100, 23, 23, 100, 23, 23, 100, 23, '1x', 90};
grid.RowSpacing = 2;
saveIcon = [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'save.png'];
searchIcon = [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'search.png'];

%% create StimControl session select
scCol = 1;
sessionConfigFilesList = getFilesList(obj.path.sessionBase, '.json');
obj.h.SessionSelectDropDown= uidropdown(grid, ...
    'Editable', 'on', 'Items', [{'Auto'} {'Browse...'} sessionConfigFilesList{2:end}], ...
    'ValueChangedFcn', @(src, event) obj.callbackLoadConfig(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol));

obj.h.saveSessionBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event) obj.callbackSaveConfig(src, event), ...
    'Icon', saveIcon, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol + 1), ...
    'Text', '');

sessionLabel = uilabel(grid, 'Text', 'Session Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [scCol scCol+1]));


savCol = scCol + 3;
obj.h.SavePathTextArea = uitextarea(grid, ...
    'Editable', 'on', 'Value', obj.path.dirData, ...
    'ValueChangedFcn', @(src, event) obj.callbackChangeSavePath(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', [savCol savCol+3]));

obj.h.BrowseSavePathBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event) obj.callbackChangeSavePath(src, event), ...
    'Icon', searchIcon, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', savCol + 4), ...
    'Text', '');

SavePathLabel = uilabel(grid, 'Text', 'Save Path', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [savCol savCol+1]));

%% create component edit button
obj.h.debugComponentBtn = uibutton(grid, ...
    'WordWrap', 'on', 'Text', 'Debug Component', ...
    'ButtonPushedFcn',@(src, event)obj.callbackDebug(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [length(grid.RowHeight) - 1, length(grid.RowHeight)], ...
        'Column', length(grid.ColumnWidth)));

%% Create Component Table
obj.h.AvailableHardwareTable = uitable('Parent', grid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [1 length(grid.ColumnWidth)]), ...
    'ColumnSortable', true, ...
    'SelectionType', 'row', ...
    'ColumnEditable', [false false true false true true true true], ...
    'SelectionChangedFcn', @obj.callbackEditComponentConfig, ...
    'CellEditCallback', @obj.callbackUpdateComponentTable);
    
    obj.callbackUpdateComponentTable([], "CreateTable"); % update (create) table data
end