function createPanelSetupControl(obj, hPanel, ~)
grid = uigridlayout(hPanel);
grid.RowHeight = {'1x', '0.01x', 22, 22};
grid.ColumnWidth = {100, 23, 23, 100, 23, 23, 100, 23, '1x', 90};
grid.RowSpacing = 2;
saveIcon = [obj.path.base filesep '@StimControl' filesep 'icons' filesep 'save.png'];

%% create StimControl session select
scCol = 1;
sessionConfigFilesList = getFilesList(obj.path.sessionBase, '.json');
obj.h.SessionSelectDropDown= uidropdown(grid, ...
    'Editable', 'on', 'Items', [{'Auto'} {'Browse...'} sessionConfigFilesList{2:end}], ...
    'ValueChangedFcn', @(src, event) obj.callbackLoadConfig(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol));

obj.h.saveSessionBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event) obj.callbackSaveConfig(src, event), ...
    'Icon', saveIcon, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight), ...
        'Column', scCol + 1), ...
    'Text', '');

sessionLabel = uilabel(grid, 'Text', 'Session Config', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', length(grid.RowHeight) - 1, ...
        'Column', [scCol scCol+1]));

% %% create hardware config select
% ccCol = scCol + 3;
% componentConfigFilesList = getFilesList(obj.path.paramBase, '.json');
% obj.h.ComponentConfigDropDown = uidropdown(grid, ...
%     'Editable', 'on', 'Items', [{'Auto'} {'Browse...'} componentConfigFilesList{2:end}], ...
%     'ValueChangedFcn', @(src, event) obj.callbackLoadConfig(src, event), ...
%     'Layout', matlab.ui.layout.GridLayoutOptions( ...
%         'Row', length(grid.RowHeight), ...
%         'Column', ccCol));
% 
% obj.h.createConfigBtn = uibutton(grid, ...
%     'ButtonPushedFcn', @(src, event) obj.callbackSaveConfig(src, event), ...
%     'Icon', saveIcon, ...
%     'Text', '', ...
%     'Layout', matlab.ui.layout.GridLayoutOptions( ...
%         'Row', length(grid.RowHeight), ...
%         'Column', ccCol + 1));
% 
% configLabel = uilabel(grid, 'Text', 'Hardware Config', ...
%     'Layout', matlab.ui.layout.GridLayoutOptions( ...
%         'Row', length(grid.RowHeight) - 1, ...
%         'Column', [ccCol ccCol+1]));

%% create component edit button
obj.h.debugComponentBtn = uibutton(grid, ...
    'WordWrap', 'on', 'Text', 'Debug Component', ...
    'ButtonPushedFcn',@(src, event)obj.callbackDebug(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', [length(grid.RowHeight) - 1, length(grid.RowHeight)], ...
        'Column', length(grid.ColumnWidth)));

%% Create Component Table
obj.h.AvailableHardwareTable = uitable('Parent', grid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [1 length(grid.ColumnWidth)]), ...
    'ColumnSortable', true, ...
    'SelectionType', 'row', ...
    'ColumnEditable', [false false true false true true true true], ...
    'SelectionChangedFcn', @obj.callbackEditComponentConfig, ...
    'CellEditCallback', @obj.callbackUpdateComponentTable);

%% Populate Component Table
columnNames = {'Type', 'ID', 'ProtocolID', 'Status', 'Enable', 'Preview', 'PRow', 'PColumn'};
tData = table();
available = obj.d.Available;
if isempty(obj.d.Available) % prevent errors with no hardware attached
    return
end
for i = 1:length(obj.d.Available)
    device = obj.d.Available{i};
    tData(end+1, :) = {class(device), ...
                        device.ComponentID, ...
                        device.ConfigStruct.ProtocolID, ...
                        device.GetStatus, ...
                        ~isempty(device.SessionHandle), ...
                        device.Previewing, ...
                        cellstr(num2str(device.PreviewPlot.Parent.Parent.Layout.Row)), ...
                        cellstr(num2str(device.PreviewPlot.Parent.Parent.Layout.Column))};
end

tData.Properties.VariableNames = columnNames;
obj.h.AvailableHardwareTable.Data = tData;
end