function createPanelSessionControl(obj, hPanel, ~)
% CREATEPANELSESSIONCONTROL creates the session control panel, with
% execution control buttons
grid = uigridlayout(hPanel);
grid.RowHeight = {22, 22, 5, 22, 22, 5, 22, 22, 5, 80, 5, '1x'};
grid.ColumnWidth = {22, '1x', '0.5x', '0.5x', '1x', 22};
grid.RowSpacing = 1;
nCols = length(grid.ColumnWidth);
nRows = length(grid.RowHeight);

%% create animal select section
aRow = 1;
obj.h.animalLabel = uilabel(grid, 'Text', 'Animal ID', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow, ...
        'Column', [1 nCols]));

obj.h.animalSelectDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', getFilesList(obj.path.dirData, ''), ...
    'ValueChangedFcn', @(src, event)obj.callbackSelectAnimal(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow + 1, ...
        'Column', [1 nCols-1]));

obj.h.newAnimalBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event)obj.callbackSelectAnimal(src, event), ...
    'Text', '+', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', aRow + 1, ...
        'Column', nCols));

%% Create experiment / protocol select section
protRow = aRow + 3;
obj.h.protocolNameLabel = uilabel(grid, 'Text', 'Protocol', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', protRow, ...
        'Column', [1 floor(nCols/2)]));
obj.h.protocolTimeEstimate = uilabel(grid, 'Text', '00:00:00 / 00:00:00', ...
    'HorizontalAlignment', 'right', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', protRow, ...
        'Column', [ceil(nCols/2) nCols]));

protocolFilesList = getFilesList(obj.path.protocolBase, {'.stim', '.qst'});
obj.path.protocolDirectories = [];
obj.h.protocolSelectDropDown = uidropdown(grid, ...
    'Editable', 'on', 'Items', [{''} protocolFilesList{:} {'Browse...'}], ...
    'ValueChangedFcn', @(src, event)obj.callbackLoadProtocol(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', protRow + 1, ...
        'Column', [1 nCols]));

%% create trial select section
tRow = protRow + 3;
obj.h.trialLabel = uilabel(grid, 'Text', 'Trial', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow, ...
        'Column', [1 floor(nCols/2)]));
obj.h.trialTimeEstimate = uilabel(grid, 'Text', '00:00 / 00:00', ...
    'HorizontalAlignment', 'right', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow, ...
        'Column', [ceil(nCols/2) nCols]));

obj.h.prevTrialBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event)obj.callbackLoadTrial(src, event), ...
    'Text', '<', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', 1));

obj.h.nextTrialBtn = uibutton(grid, ...
    'ButtonPushedFcn', @(src, event)obj.callbackLoadTrial(src, event), ...
    'Text', '>', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', nCols));

obj.h.totalTrialsLabel = uilabel(grid, ...
    'Text', '/Total', 'HorizontalAlignment', 'Left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', [ceil(nCols/2)+1 nCols-1]));

obj.h.trialNumDisplay = uieditfield(grid, 'numeric', ...
    'ValueChangedFcn', @(src, event)obj.callbackLoadTrial(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', tRow + 1, ...
        'Column', [2 floor(nCols/2)]));

%% create start/stop buttons
sessionCtrlRow = tRow + 3;
sessionCtrlGrid = uigridlayout(grid, ...
    'RowHeight', {'1x', '1x'}, ...
    'ColumnWidth', {'1x', '1x'}, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', sessionCtrlRow, ...
        'Column',[1 nCols]), ...
    'Padding', [0 0 0 0], ...
    'RowSpacing', 2, ...
    'ColumnSpacing', 2);

obj.h.StartStopBtn = uibutton(sessionCtrlGrid, ...
    'Text', 'START', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @(src, event)obj.callbackStartStop(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 1), ...
    'Enable', 'off');

obj.h.pauseBtn = uibutton(sessionCtrlGrid, ...
    'Text', 'PAUSE', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @(src, event)obj.callbackPauseResume(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 2), ...
    'Enable', 'off');

obj.h.StartPassiveBtn = uibutton(sessionCtrlGrid, ...
    'Text', 'START PASSIVE', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @(src, event)obj.callbackStartStop(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', 1), ...
    'Enable', 'off');

obj.h.StartSingleTrialBtn = uibutton(sessionCtrlGrid, ...
    'Text', 'SINGLE TRIAL', 'WordWrap', 'on', ...
    'ButtonPushedFcn', @(src, event)obj.callbackStartStop(src, event), ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', 2), ...
    'Enable', 'off');

%% create information panel
sessionInformationPanel = uipanel(grid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', nRows, ...
        'Column', [1 nCols]));

infoGrid = uigridlayout(sessionInformationPanel, ...
    'RowHeight', {23, 23, '1x'}, ...
    'ColumnWidth', {20, '1x', '1x', 20}, ...
    'RowSpacing', 2);

niRows = length(infoGrid.RowHeight);
niCols = length(infoGrid.ColumnWidth);

obj.h.statusLamp = uilamp(infoGrid, ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 1), ...
    'Color', '#808080');

obj.h.statusLabel = uilabel(infoGrid, ...
    'Text', 'Not Initialised', 'HorizontalAlignment', 'left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [2 niCols]));

obj.h.loadingLabel = uilabel(infoGrid, ...
    'Text', 'loading', 'HorizontalAlignment', 'left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [2 niCols]), ...
        'Visible', 'off');

obj.h.StatusCountdownLabel = uilabel(infoGrid, ...
    'Text', '-00:00', 'HorizontalAlignment', 'right', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', [1 niCols]));

obj.h.numTrialsElapsedLabel = uilabel(infoGrid, ...
    'Text', 'Trial 0/0', 'HorizontalAlignment', 'left', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', niRows-1, ...
        'Column', [1 niCols]));

obj.h.trialInformationScroller = uitextarea(infoGrid, ...
    'Editable', 'off', ...
    'Value', '', ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', niRows, ...
        'Column', [1 niCols]));

obj.h.sessionInformationPanel.panel.params = sessionInformationPanel;
end