function createPanelSessionHardware(obj, hPanel, ~)
% CREATEPANELSESSIONHARDWARE creates the panel for status of session
% hardware. 
numComponents = obj.d.nActive;
grid = uigridlayout(hPanel);
grid.RowHeight = {'1x'};
grid.ColumnWidth = repmat({'1x'}, 1, numComponents + 1);
grid.RowSpacing = 2;
nCols = length(grid.ColumnWidth);
nRows = length(grid.RowHeight);
obj.h.timerStatusPanel = uipanel(grid, ...
    "Title", "State Machine Timer", ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', 1));
for i = 2:numComponents+1
    component = obj.d.activeComponents{i-1};
    component.statusPanel = uipanel(grid, ...
        'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 1, ...
        'Column', i));
    component.CreateStatusDisplay;
end

obj.h.SessionHardwareGrid = grid;

timerStatusGrid = uigridlayout(obj.h.timerStatusPanel, ...
        'RowHeight', {'1x', '1x'}, ...
        'ColumnWidth', {'0.2x', '1x'}, ...
        'Padding', [0 0 0 0], ...
        'RowSpacing', 2);
obj.h.TimerLastUpdatedLabel = uilabel(timerStatusGrid, ...
    "Text", "LastUpdated", ...
    'Layout', matlab.ui.layout.GridLayoutOptions( ...
        'Row', 2, ...
        'Column', [1 2]), ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'center');
end