function createFigure(obj)
% https://au.mathworks.com/help/matlab/creating_guis/choose-components-for-your-app-designer-app.html
% https://au.mathworks.com/help/matlab/creating_guis/create-and-run-a-simple-programmatic-app.html
% https://au.mathworks.com/help/matlab/develop-apps-programmatically.html?s_tid=CRUX_lftnav

obj.h.fig = figure(...
    'Position',         [200 200 900 648], ...
    'Units',            'Pixels', ...
    'Name',             obj.name, ...
    'Resize',           'off', ...
    'DockControl',      'off', ...
    'NumberTitle',      'off', ...
    'MenuBar',          'none', ...
    'Visible',          'off', ...
    'CloseRequestFcn',  @obj.callbackFileExit, ...
    'GraphicsSmoothing','on');

obj.h.mainGrid = uigridlayout(obj.h.fig);
obj.h.mainGrid.RowHeight = {'1x', 100, 100};
obj.h.mainGrid.ColumnWidth = {'1x', 100};

obj.h.FileControl.panel.params = uipanel(obj.h.fig, ...
    'CreateFcn', @obj.createPanelFileControl);

% % create LED panel
% obj.h.LED.panel.params = uipanel(obj.h.fig,...
% 	'CreateFcn',        @obj.createPanelLED);
% 
% % create thermode panels
% for ii = fliplr(1:length(obj.s))
%     thermodeID = ['Thermode' char(64+ii)];
%     obj.h.(thermodeID).panel.params = uipanel(obj.h.fig,...
%         'CreateFcn',    {@obj.createPanelThermode,ii,length(obj.s)});
% end
% 
% % synchronize axes
% tmp = fieldnames(obj.h);
% tmp = tmp(~cellfun(@(x) isempty(regexp(x,'^Thermode|LED','once')),tmp));
% linkaxes(cellfun(@(x) obj.h.(x).axes,tmp),'x')
% 
% % create remaining panels
% obj.h.animal.panel.main      = uipanel(obj.h.fig,...
%     'CreateFcn',    @obj.createPanelAnimal);
% obj.h.protocol.panel.main    = uipanel(obj.h.fig,...
%     'CreateFcn',    @obj.createPanelProtocol);
% obj.h.singleRun.panel.main    = uipanel(obj.h.fig,...
%     'CreateFcn',    @obj.createPanelSingleRun);
% 
% % resize figure
% obj.h.fig.Position(4) = sum(obj.h.singleRun.panel.main.Position([2 4]))+10;
% 
% % create menu
% obj.h.menu.file     = uimenu(...
%     'Label',        'File');
% obj.h.menu.fileOpen	= uimenu(obj.h.menu.file,...
%     'Label',        'Open ...', ...
%     'Accelerator',  'O', ...
%     'Callback',     @obj.callbackFileOpen);
% obj.h.menu.fileClose= uimenu(obj.h.menu.file,...
%     'Label',        'Close', ...
%     'Enable',       'Off', ...
%     'Callback',     @obj.callbackFileClose);
% obj.h.menu.fileExit	= uimenu(obj.h.menu.file,...
%     'Label',        'Exit', ...
%     'Separator',    'on', ...
%     'Callback',     @obj.callbackFileExit);
% obj.h.menu.debug 	= uimenu(...
%     'Label',        'Debug');
% obj.h.menu.debugKB	= uimenu(obj.h.menu.debug,...
%     'Label',        'Keyboard', ...
%     'Callback',     @obj.callbackDebugKB);
% obj.h.menu.debugCB  = uimenu(obj.h.menu.debug,...
%     'Label',        'Copy Parameters', ...
%     'Callback',     @obj.callbackDebugCB);
% obj.h.menu.debugDel = uimenu(obj.h.menu.debug,...
%     'Label',        'Delete Unused Animal IDs', ...
%     'Callback',     @obj.callbackDebugDelEmpty);
% 
% obj.h = orderfields(obj.h);
% movegui(obj.h.fig,'center')
% obj.h.fig.Visible = 'on';